# fly.toml app configuration file for client
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pdf-learning-saas-client'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  NODE_ENV = "production"

# Health check configuration
[[services.http_checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/"
  protocol = "https"
  tls_skip_verify = false

# Static asset configuration
[http_service.concurrency]
  type = "requests"
  hard_limit = 200
  soft_limit = 100
